root: nep.al
resources:
  - home
  - post
  - domain
tweaks:
  controller:
    home.home:
      path: / # this path is primary
      allowed_methods: [ GET, POST ]
      unique: true
  path:
    /favicon.ico: # this path is secondary
      controller: error_handler.not_found
