root: home.home # this path can't be overridden
resources:
  - home
tweaks:
  controller:
    home.home:
      path: / # this path is primary
      allowed_methods: [ GET ]

  path:
    /favicon.ico: # this path is secondary
      controller: home.home
