resources:
  - home
  - post
tweaks:
  controller:
    home.home:
      path: /happy/ # this path is primary
      allowed_methods: [ GET ]
      unique: true
  path:
    /favicon.ico: # this path is secondary
      controller: home.home
